In [2]:
import pandas as pd
import streamlit as st
import numpy as np

In [87]:
# importing datasets

providers_data = pd.read_csv('providers_data.csv')
receivers_data = pd.read_csv('receivers_data.csv')
food_listings_data = pd.read_csv('food_listings_data.csv')
claims_data = pd.read_csv('claims_data.csv')

In [97]:
# understanding datasets

providers_data.info()
claims_data.info()
food_listings_data.info()
receivers_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Provider_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Type         1000 non-null   object
 3   Address      1000 non-null   object
 4   City         1000 non-null   object
 5   Contact      1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Claim_ID     1000 non-null   int64
 1   Food_ID      1000 non-null   int64
 2   Receiver_ID  1000 non-null   int64
 3   Status       1000 non-null   object
 4   Timestamp    1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_ID        1000 non-null   int64
 1   Food_Name      1000 non-null   object
 2   Quantity       1000 non-null   int64
 3   Expiry_Date    1000 non-null   object
 4   Provider_ID    1000 non-null   int64
 5   Provider_Type  1000 non-null   object
 6   Location       1000 non-null   object
 7   Food_Type      1000 non-null   object
 8   Meal_Type      1000 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Receiver_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Type         1000 non-null   object
 3   City         1000 non-null   object
 4   Contact      1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

In [99]:
  #converting to datetime
food_listings_data["Expiry_Date"] = pd.to_datetime(food_listings_data["Expiry_Date"], errors="coerce")

claims_data["Timestamp"] = pd.to_datetime(claims_data["Timestamp"], errors="coerce")

In [101]:
  #Create SQL Database & Load Data

import sqlite3

# Load CSVs
providers_df = pd.read_csv("providers_data.csv")
receivers_df = pd.read_csv("receivers_data.csv")
food_df = pd.read_csv("food_listings_data.csv")
claims_df = pd.read_csv("claims_data.csv")

# Convert date columns
food_df["Expiry_Date"] = pd.to_datetime(food_df["Expiry_Date"], errors="coerce")
claims_df["Timestamp"] = pd.to_datetime(claims_df["Timestamp"], errors="coerce")

# Connect to SQLite DB (creates file if not exists)
conn = sqlite3.connect("food_wastage.db")
cursor = conn.cursor()

# Create Providers Table
cursor.execute("""
CREATE TABLE IF NOT EXISTS Providers (
    Provider_ID INTEGER PRIMARY KEY,
    Name TEXT,
    Type TEXT,
    Address TEXT,
    City TEXT,
    Contact TEXT
)
""")

# Create Receivers Table
cursor.execute("""
CREATE TABLE IF NOT EXISTS Receivers (
    Receiver_ID INTEGER PRIMARY KEY,
    Name TEXT,
    Type TEXT,
    City TEXT,
    Contact TEXT
)
""")

# Create Food Listings Table
cursor.execute("""
CREATE TABLE IF NOT EXISTS Food_Listings (
    Food_ID INTEGER PRIMARY KEY,
    Food_Name TEXT,
    Quantity INTEGER,
    Expiry_Date DATE,
    Provider_ID INTEGER,
    Provider_Type TEXT,
    Location TEXT,
    Food_Type TEXT,
    Meal_Type TEXT,
    FOREIGN KEY (Provider_ID) REFERENCES Providers(Provider_ID)
)
""")

# Create Claims Table
cursor.execute("""
CREATE TABLE IF NOT EXISTS Claims (
    Claim_ID INTEGER PRIMARY KEY,
    Food_ID INTEGER,
    Receiver_ID INTEGER,
    Status TEXT,
    Timestamp DATETIME,
    FOREIGN KEY (Food_ID) REFERENCES Food_Listings(Food_ID),
    FOREIGN KEY (Receiver_ID) REFERENCES Receivers(Receiver_ID)
)
""")

# Insert DataFrames into DB
providers_df.to_sql("Providers", conn, if_exists="replace", index=False)
receivers_df.to_sql("Receivers", conn, if_exists="replace", index=False)
food_df.to_sql("Food_Listings", conn, if_exists="replace", index=False)
claims_df.to_sql("Claims", conn, if_exists="replace", index=False)

conn.commit()
conn.close()

print("✅ Database created and data inserted successfully!")

✅ Database created and data inserted successfully!

In [103]:

DB_NAME = "food_wastage.db"

# -------------------------
# Generic Helper -- 
# this is to reduce the generic boilerplate code which is making connection to our DB, commiting changes and closing connection
# -------------------------
def run_query(query, params=(), fetchone=False, fetchall=False):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute(query, params)
    conn.commit()
    result = None
    if fetchone:
        result = cursor.fetchone()
    elif fetchall:
        result = cursor.fetchall()
    conn.close()
    return result


# -------------------------
# Providers CRUD
# -------------------------
def add_provider(provider_id, name, type_, address, city, contact):
    run_query("""
        INSERT INTO Providers (Provider_ID, Name, Type, Address, City, Contact)
        VALUES (?, ?, ?, ?, ?, ?)
    """, (provider_id, name, type_, address, city, contact))

def get_provider_by_id(provider_id):
    return run_query("SELECT * FROM Providers WHERE Provider_ID = ?", (provider_id,), fetchone=True)

def get_providers():
    return run_query("SELECT * FROM Providers", fetchall=True)

def update_provider(provider_id, **kwargs):
    updates = ", ".join([f"{col} = ?" for col in kwargs.keys()])
    values = list(kwargs.values())
    values.append(provider_id)
    query = f"UPDATE Providers SET {updates} WHERE Provider_ID = ?"
    run_query(query, tuple(values))

def delete_provider(provider_id):
    run_query("DELETE FROM Providers WHERE Provider_ID = ?", (provider_id,))


# -------------------------
# Receivers CRUD
# -------------------------
def add_receiver(receiver_id, name, type_, city, contact):
    run_query("""
        INSERT INTO Receivers (Receiver_ID, Name, Type, City, Contact)
        VALUES (?, ?, ?, ?, ?)
    """, (receiver_id, name, type_, city, contact))

def get_receiver_by_id(receiver_id):
    return run_query("SELECT * FROM Receivers WHERE Receiver_ID = ?", (receiver_id,), fetchone=True)

def get_receivers():
    return run_query("SELECT * FROM Receivers", fetchall=True)

def update_receiver(receiver_id, **kwargs):
    updates = ", ".join([f"{col} = ?" for col in kwargs.keys()])
    values = list(kwargs.values())
    values.append(receiver_id)
    query = f"UPDATE Receivers SET {updates} WHERE Receiver_ID = ?"
    run_query(query, tuple(values))

def delete_receiver(receiver_id):
    run_query("DELETE FROM Receivers WHERE Receiver_ID = ?", (receiver_id,))


# -------------------------
# Food Listings CRUD
# -------------------------
def add_food(food_id, food_name, quantity, expiry_date, provider_id, provider_type, location, food_type, meal_type):
    run_query("""
        INSERT INTO Food_Listings (Food_ID, Food_Name, Quantity, Expiry_Date, Provider_ID, Provider_Type, Location, Food_Type, Meal_Type)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (food_id, food_name, quantity, expiry_date, provider_id, provider_type, location, food_type, meal_type))

def get_food_by_id(food_id):
    return run_query("SELECT * FROM Food_Listings WHERE Food_ID = ?", (food_id,), fetchone=True)

def get_food_listings():
    return run_query("SELECT * FROM Food_Listings", fetchall=True)

def update_food(food_id, **kwargs):
    updates = ", ".join([f"{col} = ?" for col in kwargs.keys()])
    values = list(kwargs.values())
    values.append(food_id)
    query = f"UPDATE Food_Listings SET {updates} WHERE Food_ID = ?"
    run_query(query, tuple(values))

def delete_food(food_id):
    run_query("DELETE FROM Food_Listings WHERE Food_ID = ?", (food_id,))


# -------------------------
# Claims CRUD
# -------------------------
def add_claim(claim_id, food_id, receiver_id, status, timestamp):
    run_query("""
        INSERT INTO Claims (Claim_ID, Food_ID, Receiver_ID, Status, Timestamp)
        VALUES (?, ?, ?, ?, ?)
    """, (claim_id, food_id, receiver_id, status, timestamp))

def get_claim_by_id(claim_id):
    return run_query("SELECT * FROM Claims WHERE Claim_ID = ?", (claim_id,), fetchone=True)

def get_claims():
    return run_query("SELECT * FROM Claims", fetchall=True)

def update_claim(claim_id, **kwargs):
    updates = ", ".join([f"{col} = ?" for col in kwargs.keys()])
    values = list(kwargs.values())
    values.append(claim_id)
    query = f"UPDATE Claims SET {updates} WHERE Claim_ID = ?"
    run_query(query, tuple(values))

def delete_claim(claim_id):
    run_query("DELETE FROM Claims WHERE Claim_ID = ?", (claim_id,))

In [105]:


def run_sql(query, params=()):
    """Helper to run SQL and return DataFrame"""
    conn = sqlite3.connect(DB_NAME)
    df = pd.read_sql_query(query, conn, params=params)
    conn.close()
    return df

# -------------------------
# Providers & Receivers
# -------------------------

def providers_per_city():
    return run_sql("SELECT City, COUNT(*) AS Provider_Count FROM Providers GROUP BY City;")

def receivers_per_city():
    return run_sql("SELECT City, COUNT(*) AS Receiver_Count FROM Receivers GROUP BY City;")

def top_provider_types():
    return run_sql("""
        SELECT Provider_Type, SUM(Quantity) AS Total_Quantity
        FROM Food_Listings
        GROUP BY Provider_Type
        ORDER BY Total_Quantity DESC;
    """)

def provider_contacts_by_city(city):
    return run_sql("SELECT Name, Contact FROM Providers WHERE City = ?", (city,))

def top_receivers(limit=10):
    return run_sql("""
        SELECT r.Name, COUNT(c.Claim_ID) AS Total_Claims
        FROM Claims c
        JOIN Receivers r ON c.Receiver_ID = r.Receiver_ID
        GROUP BY r.Name
        ORDER BY Total_Claims DESC
        LIMIT ?;
    """, (limit,))

In [144]:
# -------------------------
# Food Listings & Availability
# -------------------------

def total_food_available():
    return run_sql("SELECT SUM(Quantity) AS Total_Food_Available FROM Food_Listings;")

def city_with_most_listings():
    return run_sql("""
        SELECT Location, COUNT(*) AS Total_Listings
        FROM Food_Listings
        GROUP BY Location
        ORDER BY Total_Listings DESC
        LIMIT 1;
    """)

def common_food_types():
    return run_sql("""
        SELECT Food_Type, COUNT(*) AS Count_Type
        FROM Food_Listings
        GROUP BY Food_Type
        ORDER BY Count_Type DESC;
    """)

In [109]:
# -------------------------
# Claims & Distribution
# -------------------------

def claims_per_food(limit=10):
    return run_sql("""
        SELECT f.Food_Name, COUNT(c.Claim_ID) AS Claim_Count
        FROM Claims c
        JOIN Food_Listings f ON c.Food_ID = f.Food_ID
        GROUP BY f.Food_Name
        ORDER BY Claim_Count DESC
        LIMIT ?;
    """, (limit,))

def top_successful_provider():
    return run_sql("""
        SELECT p.Name, COUNT(c.Claim_ID) AS Successful_Claims
        FROM Claims c
        JOIN Food_Listings f ON c.Food_ID = f.Food_ID
        JOIN Providers p ON f.Provider_ID = p.Provider_ID
        WHERE c.Status = 'Completed'
        GROUP BY p.Name
        ORDER BY Successful_Claims DESC
        LIMIT 1;
    """)

def claim_status_percentage():
    return run_sql("""
        SELECT Status,
               ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Claims), 2) AS Percentage
        FROM Claims
        GROUP BY Status;
    """)

In [188]:
# -------------------------
# Analysis & Insights
# -------------------------

def avg_quantity_per_receiver(limit=10):
    return run_sql("""
        SELECT r.Name, ROUND(AVG(f.Quantity),2) AS Avg_Quantity_Claimed
        FROM Claims c
        JOIN Receivers r ON c.Receiver_ID = r.Receiver_ID
        JOIN Food_Listings f ON c.Food_ID = f.Food_ID
        WHERE c.Status = 'Completed'
        GROUP BY r.Name
        ORDER BY Avg_Quantity_Claimed DESC
        LIMIT ?;
    """, (limit,))

def most_claimed_meal_type():
    return run_sql("""
        SELECT f.Meal_Type, COUNT(c.Claim_ID) AS Total_Claims
        FROM Claims c
        JOIN Food_Listings f ON c.Food_ID = f.Food_ID
        WHERE c.Status = 'Completed'
        GROUP BY f.Meal_Type
        ORDER BY Total_Claims DESC;
    """)

def total_donated_per_provider(limit=10):
    return run_sql("""
        SELECT p.Name, SUM(f.Quantity) AS Total_Donated
        FROM Providers p
        JOIN Food_Listings f ON p.Provider_ID = f.Provider_ID
        GROUP BY p.Name
        ORDER BY Total_Donated DESC
        LIMIT ?;
    """, (limit,))

def top_donated_foods(limit=5):
    return run_sql("""
        SELECT Food_Name, COUNT(*) AS Donation_Count
        FROM Food_Listings
        GROUP BY Food_Name
        ORDER BY Donation_Count DESC
        LIMIT ?;
    """, (limit,))